### ISSUE TITLE
[REQ] fix license file

### ISSUE THREAD

**Issue by MarcoRavich** [brummer10/LittleFly.lv2#2]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO category](https://github.com/forart/HyMPS#- ) \ [Effects page](https://github.com/forart/HyMPS/blob/main/Audio/Effects.md#-- ) \ [Guitar section](https://github.com/forart/HyMPS/blob/main/Audio/Guitar.md#--- ) \ [Pedals subsection](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#---- ) \ [Overdrive](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#overdrive-)), can you please fix the license file for it ?

Although it may sounds like a minor aspect, license file uncompliance obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/brummer10/LittleFly.lv2/)
(badge-generator URL: https://flat.badgen.net/github/license/brummer10/LittleFly.lv2/)

For example, check the [wikimedia's Fresh git](https://github.com/wikimedia/fresh/blob/master/LICENSE-0BSD) to visualize an example of how the BSD0 license needs to be formatted to let GH interprets it correctly. And, of course, its badge:

![](https://flat.badgen.net/github/license/wikimedia/fresh/)
(badge-generator URL: https://flat.badgen.net/github/license/wikimedia/fresh/)

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by brummer10** [comment]
done

**Comment by MarcoRavich** [comment]
Thank you very mutch, it works now.
